"""
Django settings for gen_ai project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import environ
import os

# Setting up environment variable connect
env = environ.Env(DEBUG=(bool, True))
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$soe01v@-_pe*u%2i9*#c1avt8nld4x&-h#=l&o!0n=r$zc%q0'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
CORS_ORIGIN_ALLOW_ALL = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'django_crontab',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# MIDDLEWARE = MIDDLEWARE + ['chat_apis.okta_middleware.APIAuthMiddleware']

CRONJOBS = [
    ('0 5 * * 0', 'chat_apis.cron.my_scheduled_job')
]

# Here are short descriptions of the Django crontab commands:

# python manage.py crontab add: This command adds scheduled tasks to the crontab for the current Django project. It registers the defined cron jobs in your Django application.

# python manage.py crontab show: This command displays the current cron jobs that are scheduled for your Django project. It helps you verify which tasks are set up to run.

# python manage.py crontab remove: This command removes all scheduled tasks from the crontab for your Django project. It cleans up the cron jobs that were previously added.

ROOT_URLCONF = 'gen_ai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gen_ai.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



# Checking for environment variables

# OPEN AI
CHAT_MODEL_NAME = env.str('CHAT_MODEL_NAME')
EMBEDDING_MODEL_NAME = env.str("EMBEDDING_MODEL_NAME")
RANKER_MODEL_NAME = env.str("RANKER_MODEL_NAME")
OPENAI_API_KEY = env.str("OPENAI_API_KEY")

# MONGO CONNECTIONS
MONGO_CONNECTION_STRING = env.str("MONGO_CONNECTION_STRING")
MONGO_DB = env.str("MONGO_DB")
USER_DETAILS_COLLECTION = env.str("USER_DETAILS_COLLECTION")
FAQ_COLLECTION = env.str('FAQ_COLLECTION')
CHAT_COLLECTION = env.str('CHAT_COLLECTION')
CHAT_MSG_COLLECTION = env.str('CHAT_MSG_COLLECTION')
UPLOAD_META_COLLECTION = env.str('UPLOAD_META_COLLECTION')
SUB_COLLECTION = env.str('SUB_COLLECTION')

#MILVUS
MILVUS_HOST = env.str("MILVUS_HOST")
MILVUS_PORT = env.int("MILVUS_PORT")

# AWS S3 CONNEECTIONS
BUCKET_NAME = env.str("S3_BUCKET_NAME")
AWS_ACCESS_KEY_ID = env.str("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = env.str("AWS_SECRET_ACCESS_KEY")
AWS_DEFAULT_REGION = env.str("AWS_DEFAULT_REGION")
ROLEARN = env.str('ROLEARN')

# LANGFUSE_SECRET_KEY = 
# LANGFUSE_PUBLIC_KEY = 
# LANGFUSE_HOST = 'http://localhost:3000'

########################### Logger #############################################
LOGS_PATH = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOGS_DIR = os.path.join(LOGS_PATH, 'logs')

if not os.path.exists(LOGS_DIR):
    os.mkdir(LOGS_DIR)
    
LOGGING = {
    'version':1,
    'disable_existing_loggers': False,
    'handlers':{
        'file':{
            'level':'INFO',
            'class':'logging.handlers.RotatingFileHandler',
            'filename': os.path.join(LOGS_DIR, 'companion.log'),
            'maxBytes':1024 * 1024 * 5,
            'backupCount':5,
            'formatter':'verbose',
        },
        'console':{
            'level':'INFO',
            'class':'logging.StreamHandler',
            'formatter':'verbose',
        },
    },
    'loggers':{
        'django':{
            'handlers':['file', 'console'],
            'level':'INFO',
            'propagate':True,
        },
        '':{
            'handlers':['file'],
            'level':'INFO',
            'propagate':True,
        },
    },
    'formatters':{
        'verbose':{
            'format':'%(asctime)s - %(levelname)s [%(name)s:%(lineno)s] %(message)s'
        },
    },
}